### ISSUE TITLE
rsplit error

### ISSUE THREAD

**Issue by saraneem** [Anaconda-Platform/ae5-tools#127]
`ae5 job list` and few other list commands throws the below error:

> File "/opt/anaconda/miniconda3/envs/ae5tools/bin/ae5", line 10, in <module>
> sys.exit(main())
> File "/opt/anaconda/miniconda3/envs/ae5tools/lib/python3.8/site-packages/ae5_tools/cli/main.py", line 148, in main
> cli(obj={})
> File "/opt/anaconda/miniconda3/envs/ae5tools/lib/python3.8/site-packages/click/core.py", line 829, in __call__
> return self.main(*args, **kwargs)
> File "/opt/anaconda/miniconda3/envs/ae5tools/lib/python3.8/site-packages/click/core.py", line 782, in main
> rv = self.invoke(ctx)
> File "/opt/anaconda/miniconda3/envs/ae5tools/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
> return _process_result(sub_ctx.command.invoke(sub_ctx))
> File "/opt/anaconda/miniconda3/envs/ae5tools/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
> return _process_result(sub_ctx.command.invoke(sub_ctx))
> File "/opt/anaconda/miniconda3/envs/ae5tools/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
> return ctx.invoke(self.callback, **ctx.params)
> File "/opt/anaconda/miniconda3/envs/ae5tools/lib/python3.8/site-packages/click/core.py", line 610, in invoke
> return callback(*args, **kwargs)
> File "/opt/anaconda/miniconda3/envs/ae5tools/lib/python3.8/site-packages/ae5_tools/cli/commands/job.py", line 26, in list
> cluster_call('job_list', **kwargs)
> File "/opt/anaconda/miniconda3/envs/ae5tools/lib/python3.8/site-packages/ae5_tools/cli/login.py", line 228, in cluster_call
> result = getattr(c, method)(*args, **kwargs)
> File "/opt/anaconda/miniconda3/envs/ae5tools/lib/python3.8/site-packages/ae5_tools/api.py", line 1267, in job_list
> response = self._get_records('jobs', filter=filter)
> File "/opt/anaconda/miniconda3/envs/ae5tools/lib/python3.8/site-packages/ae5_tools/api.py", line 539, in _get_records
> return self._api_records('get', endpoint, filter=filter, **kwargs)
> File "/opt/anaconda/miniconda3/envs/ae5tools/lib/python3.8/site-packages/ae5_tools/api.py", line 536, in _api_records
> return self._fix_records(record_type, records, filter, **kwargs)
> File "/opt/anaconda/miniconda3/envs/ae5tools/lib/python3.8/site-packages/ae5_tools/api.py", line 252, in _fix_records
> records = getattr(self, pre)(records)
> File "/opt/anaconda/miniconda3/envs/ae5tools/lib/python3.8/site-packages/ae5_tools/api.py", line 1260, in _pre_job
> pid = 'a0-' + rec['project_url'].rsplit('/', 1)[-1]
> AttributeError: 'NoneType' object has no attribute 'rsplit'

version: 0.4.0

It works for some user accounts.

**Comment by mcg1969** [comment]
I'm not able to reproduce this. Can you tell me which version of AE5 this is?

**Comment by saraneem** [comment]
It is 5.4.1

**Comment by saraneem** [comment]
I see this error while trying to login:

![image](https://user-images.githubusercontent.com/26414824/110694545-5bd65d80-81ae-11eb-8fd2-413cebe87105.png)

**Comment by mcg1969** [comment]
I've been able to reproduce. Fix coming

**Comment by mcg1969** [comment]
Had to fix some failing tests but we're there, stay tuned. Will tag 0.4.1 as soon as it's done

**Comment by mcg1969** [comment]
@saraneem this has been fixed and will be working in 0.4.1, which is being built now.

**Comment by saraneem** [comment]
@mcg1969 That's great. Thanks!

**Comment by mcg1969** [comment]
@saraneem FYI, version 0.4.1 includes this fix, and is on the ae5-admin channel.

**Comment by saraneem** [comment]
cool, I will test it. Thanks, @mcg1969
